version: "3"

tasks:
  dev:
    cmds:
      - docker-compose up -d
      - cd todoapp/htmx/assets && pnpm build
      - go run cmd/todoapp/main.go || true

  build:
    cmds:
      - cd todoapp/htmx/assets && pnpm build
      - go build -o bin/try-go-htmx cmd/todoapp/main.go
