version: "3"

tasks:
  setup:
    cmds:
      - cd internal/web && pnpm install

  dev:
    cmds:
      - docker-compose up -d
      - cd internal/web && pnpm build
      - go run cmd/app/main.go || true

  build:
    cmds:
      - cd internal/web && pnpm build
      - go build -o bin/try-go-htmx cmd/app/main.go
